name: wifi_password_viewer
description: View and share your wifi passwords.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1
  dynamic_theme: ^1.0.1
  qr_flutter: ^2.0.0
  fluttertoast: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/manrope-medium.ttf
